name: view-feedback
description: "View all feedback for a PRD or Epic - grouped by section and type"
author: "BMad"
version: "1.0.0"

config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
cache_dir: "{output_folder}/cache"

github:
  owner: "{config_source}:github_owner"
  repo: "{config_source}:github_repo"

# Parameters
document_key: ""
document_type: "" # "prd" or "epic"

installed_path: "{project-root}/_bmad/bmm/workflows/1-requirements/crowdsource/view-feedback"
instructions: "{installed_path}/instructions.md"

standalone: true
