name: create-prd-draft
description: "Create a new PRD draft with stakeholder list - stored as markdown, coordinated via GitHub"
author: "BMad"
version: "1.0.0"

config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
cache_dir: "{output_folder}/cache"
docs_dir: "{project-root}/docs/prd"

github:
  owner: "{config_source}:github_owner"
  repo: "{config_source}:github_repo"

# PRD creation options
import_from: "" # 'scratch', 'existing-prd', 'product-brief'

installed_path: "{project-root}/_bmad/bmm/workflows/1-requirements/crowdsource/create-prd-draft"
instructions: "{installed_path}/instructions.md"

standalone: true
