name: synthesize-epic-feedback
description: "LLM-powered synthesis of epic feedback with story split and dependency resolution"
author: "BMad"
version: "1.0.0"

config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
cache_dir: "{output_folder}/cache"
docs_dir: "{project-root}/docs"

github:
  owner: "{config_source}:github_owner"
  repo: "{config_source}:github_repo"

# Parameters
epic_key: ""

installed_path: "{project-root}/_bmad/bmm/workflows/1-requirements/crowdsource/synthesize-epic-feedback"
instructions: "{installed_path}/instructions.md"

standalone: true
