name: create-epic-draft
description: "Create an epic from an approved PRD, splitting user stories into implementation-ready epics"
author: "BMad"
version: "1.0.0"

config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
cache_dir: "{output_folder}/cache"
docs_dir: "{project-root}/docs"

github:
  owner: "{config_source}:github_owner"
  repo: "{config_source}:github_repo"

# Parameters
source_prd: "" # PRD key to create epic from
epic_key: "" # Optional: override generated epic key
stakeholders: [] # Override default stakeholders

installed_path: "{project-root}/_bmad/bmm/workflows/1-requirements/crowdsource/create-epic-draft"
instructions: "{installed_path}/instructions.md"

standalone: true
